name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - feature/deployRelease

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm install -g babel-cli
      - run: npm run build
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

  #publish-gpr:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v1
  #    - uses: actions/setup-node@v1
  #      with:
  #        node-version: 12
  #        registry-url: https://npm.pkg.github.com/
  #        scope: '@wirths'
  #    - run: npm publish
  #      env:
  #        NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
